name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tox
        run: sudo apt-get install -y tox

      - name: Run Tox
        run: tox -c tox.ini
